/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.NaverClicker
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    NaverClicker.run()
    println(App().greeting)
}
