/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.example.naver.NaverClicker;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
            NaverClicker.run();  // NaverClicker 실행
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
